[tools]
usage = "latest"
# Prompt
starship = "latest"

kubectl = "latest"
helm = "prefix:3"
"aqua:danielfoehrKn/kubeswitch" = "latest"
"aqua:neovim/neovim" = "prefix:0.11"
uv = "latest"
terraform = "latest"

golangci-lint = "latest"
"go:gotest.tools/gotestsum" = "latest"

# Decode and validate JWTs locally
"npm:jwt-cli" = "latest"

# For neovim
"npm:tree-sitter-cli" = "latest"

# Music manager
"pipx:beets" = { version = "latest", extras = "scrub,chroma" }

# AI Tools
"npm:@github/copilot" = "latest"
"npm:mcp-hub" = "latest"
"pipx:oraios/serena" = "v0.1.4"            # MCP using LSPs
"npm:opencode-ai" = "latest"
"aqua:openai/codex" = "latest"
"npm:@zed-industries/codex-acp" = "latest"

# General purpose CLI tools
ripgrep = "latest"
fd = "latest"
jq = "latest"
fzf = "latest"
gh = "latest"
aws-cli = "latest"
